### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by antigravities** [antigravities/levelup#7]

**Comment by bikerwhocodes** [comment]
Do you want me to take over this, looks straight forward

**Comment by antigravities** [comment]
Sure, feel free!

**Comment by bikerwhocodes** [comment]
do you want me create a custom docker file or just use go and nodes docker files?

**Comment by antigravities** [comment]
Sorry, not quite sure what you mean by "use go and nodes docker files." I'm fairly new to containerization in general - so please correct me if I'm wrong - but here's how I imagined it would work:

1. Fetch the sources
2. Build the Go parts into a static executable using `GO111MODULE=on go build -i`
3. Build all of the assets using `webpack`
4. Copy the `levelup` executable and `static` directory (generated by `webpack`) into the container
5. The container starts `levelup` with some way of toggling whether the server runs in `serve` or `fetch` mode

**Comment by bikerwhocodes** [comment]
Ok got it, thanks for the clarification.

**Comment by antigravities** [comment]
Hey @bikerwhocodes! Are you still working on this? If not that's ok - appreciate the effort anyway!!

**Comment by bikerwhocodes** [comment]
Hey @antigravities im so sorry was kinda busy last week, will definitely work on it tomorrow.

**Comment by bikerwhocodes** [comment]
hey @antigravities please try this and let me know if it works. I'll give you the docker file.
`docker run --env-file .env -p 8080:4000 nihalpandit/levelup`

**Comment by antigravities** [comment]
Great work! Just gave it a try now and learned quite a bit by looking at the Dockerfile you wrote. Feel free to send a pull request whenever you're ready; thanks again for contributing!

**Comment by bikerwhocodes** [comment]
ok will do that.

**Comment by bikerwhocodes** [comment]
did u get a chance to look at the PR?

**Comment by antigravities** [comment]
Sorry for the delay - was busy at work - thanks for submitting! Just reviewed it now

**Comment by antigravities** [comment]
Thanks! Closed by #8.
